CREATE TABLE MH_PORTFOLIO_ASSETS
(PORTFOLIO    VARCHAR2(32) NOT NULL,
 ASSET        VARCHAR2(32) NOT NULL, 
 CONSTRAINT MH_PORTFOLIO_ASSETS_PK1 PRIMARY KEY (PORTFOLIO, ASSET),
 CONSTRAINT MH_PORTFOLIO_ASSETS_FK1 FOREIGN KEY (PORTFOLIO) REFERENCES MH_PORTFOLIOS (ACCOUNT)
 );
 
 DROP TABLE MH_PORTFOLIO_ASSETS;
 
 INSERT INTO MH_PORTFOLIO_ASSETS SELECT DISTINCT PORTFOLIO, ASSET FROM MH_INSTRUMENTS;
 
 COMMIT;